{% set version = "0.3.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gmd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GMD_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GMD/GMD_{{ version }}.tar.gz
  sha256: af4e147cb6162bd0608a9006901330a26e85d5c2e6ac5e2ef9f464862b6b504b

build:
  number: 1006
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-gplots
  run:
    - r-base
    - r-gplots

test:
  commands:
    - $R -e "library('GMD')"           # [not win]
    - "\"%R%\" -e \"library('GMD')\""  # [win]

about:
  home: http://CRAN.R-project.org/package=GMD
  license: GPL-2.0-or-later
  summary: GMD is a package for non-parametric distance measurement between two discrete frequency distributions.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
