travis:
  secure:
    BINSTAR_TOKEN: J3F48DNryZsB/e9HgZhX3zRdXuP3K/M84LI9MULTrhb9ggnmh8W4LyARKTWoy1suI6fjXrtWpbHPUG1+CsM0n7p9jjsmicqZESt+4RlplWaPv2OyYKCNkr5/FdxsuerGJdUawo7ShF1A0nZ6yTYJOg1uM2Qpa2DfMKXzbxailOqjKoxk5hLHGhU8eEy1bIj9ZD1RWT9heQH4DHVvR5/gJ6xBpwQH1hkfh+z+nu9py4r0VphJVktn7iXj0XdnU/+bLlKHED3avU/UOPMZTwa/RV4ZtJcwQOkKMWxSc4S2ce0nDBLJC6RTqi2IquQWXptxQxTyuleA448e1FGw1KmVjuCQlqmK3Y/JthvA1g0anSkKV/9hcUu+BlJarEjClb4C+913DUNX1zcDjaCnbUsURFZuJ5EtLH4QQL0D4ljrWO7T0j7WDJC2El0ihaUNI0ICe6lVI3LFzaYohtWtZ9Vybj/5yCJVZwmLn9SGxfjuRi4oJLzBfcfz3ibv5kUnC9+oVuTcjaQeblFWdaUfmnO3+7g6sJiT8KxoMMu3tj6mCOddSPaHBSmR3DPvaWFNE6FwCaA2k7r9pXuoMuwxOcrPTUbqs9cEiut5Mh9vlIPZkscELOU2dfmdxWmF9A+wqFf8s7ikUNJ+8mriPd1cpFugItdcK6cFqoFEkoA/NFiqmwY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
