travis:
  secure:
    BINSTAR_TOKEN: 5SRkXOeHogz87oksqnH0Q9uQir3EnHegBl4ArrBmGYW2R4B8jrw9DPxBc6PpdsRiWFKnrPxtfLcvsps2DhN4xzpNuKFsDaxyhRiN+ZTdOMu0CKYXthhIc49bFl43RqqVr2v3UO2ifRK0E/R7cLfpE8VDA12p2V+nwv016YoQwGQ9pVRjaWQFlEFcuige8KDZBDkbKYVi2gHXDbWheMXF1gI17509LH1rAKg9H7RJtir+kzTcvibFjD87aPolObog0m62SdfuusSk3tRRZR0DIULmVLcsnNBNQqcab8C9TwsRF2YcSUi5m+9TBLG0KlVAEaCx+i9wTJCRUaZ+/OmTW+t/sdWi9Grch+qMWsTnFxljm2QXqxtWK0obIuQz9nqoq6qnzBEQ6C9mRsNwIpM4kSi3ljuNLRpGUM7O3VeBpTJuTBsuF1Sn//M5QJFIcAgRIy2QlniaJ2PjUd6te2HSEi5VagN/xQPULS6c8U2Q06xt54K6sb1rTD28MnbJREGfklJiT9JRSdmLUeZi/FKQtrxHtjTD0HyMDfmt/9LF933a2kn3Uuy+Xk1i7b/6vlq75nNNbkW9aaowXwI2hjTQo7WnMblC8XkLEG7i5z2C2OuRs13ex25dLQRSeWXe1QCvjvFukovKuWOvkWMi2vGtLtOLzV4uV5dLPkO29lKXHzo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
