travis:
  secure:
    BINSTAR_TOKEN: Taxl9UA06JrFSzktNR1o/NW21Doa9ChVS7+GKPbCejBcDruFCxU4OjUOQeJB4uFB+lH8Jp4iDWBniqfeGp4dX80uA68CN/Z7MMQpmdoqrzdRRBISApHRjLr/+exeWDzLb+LzU0uwE+O6LotXvG95b7DeQb2bBDsMxdOBqQ4+dsHK/Ge9QqA92pjKQRlMCwzvq98rUFTXtuapL6UquVxj6/CDAeV4U34ZmdrTNDRYe//w7IFZL1pWwUYi7SSFCRaZclIchj23Il1jEf1/9bXkFLdD9sGGfbPk6EyaFi5m1VDE9qolYKoY5b8W4xPMsweUuOcvW6ilpDrCv/ncatGb5agZJBwnwiWgkVzlde/dclIQJJBxeIIBfd+BfMFnwIM6zM2PJaGauWydFkUNDIH9F1gkMTUgz0RyeNu+1JGWhoMfe9sZLDxwHFDLCefMI8RuXqvVyPM6aOsn4gmbQCjzw5+nV95hXOC1yPsc1SmucRf884hXWeWNDTZ8HOGTFqayG1iRSoOXYU2b9HrSvnCW4tXDuw97MByiNDAniuRXMfz3sgmVfZUQ9HQNILuG1ljB9fjnPX20yBRUO8LVZ5/xoQKeEWvGDqTiOKGBV0QDideZ3GQDi4LE4SrfZh2AE9emnUk2WG1NRCKoA2mmxdnxeR/xmDMfw7IgSBaOdbNuAtg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
