travis:
  secure:
    BINSTAR_TOKEN: hnvHTB+g7At+SWs80voeIONgSnepW9RvJfIK3fk5U0vUm99X/l3iCu71OGkX3ZrBF4B02zJBv5GdHuMCeCQLb0Qcqj1g8oatAUAiXAQ02O1SFZ1eDFEYPYna4Rt91A1NS38yi1qUVqy5wB/fMPMZDKOzKMmuTNW9nIShq9RW7QxMpIJDxaOYpTk9EMcvKxh/b27md5kVy3GCDKCxwBG+FNsQjQ1wSxGukjztS3eADqq8xZ60F5UBcrqYomPJY61t/6BnriNh7QpAI7klIXqt9NkQ4KiybZjfplZJPo0l97c/VAnSHZZU/I9YuF7RwaOoHD1heGks7+lXSeMDBRoLyvmJ2do37R1sjNB+w7FLI1Fda2UOZVO4erPj3Y1TFAZkHwA5LNwiZ1GMJmYOneOYxu7AZbbLvT+R29GrbqdZ7ogMvFmucVK0wvXqQzqf+BhMReExKTeHkYyvUflVlfsoWyF6+KBy9Wn0q1z4rZrwE9tTlWienOg3xQr2aJs/rk9gOXY/r79KgJTJUDt7WaAmmju6AYn4LijozyY6piAccibT7v/kq4c5Na0aMPUyb7UG84tDhFhKjTTtoBTxyiI0foOfrEnXg7xhU+TtwUGm045ZLTQ37HAoA+Fp/xWf7+LkDIQIWXqqyGBIlopY+MfVvKDzdvDFKtLuHgHaz/D62v8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
