travis:
  secure:
    BINSTAR_TOKEN: 1LkXWl2qlgK4vDPdo2gam1y3JWTCo+Vxx47IcWg42bPpJmIucMeBYPChYguquaSHAuKzsApnJvKi5IrmIlNlaqYPws7F+bkYpbwo0E5Ywb/MonFHjhJwvbWd8b0FJC8L7QXmDS8zcRK9enlO0DQeL1YSEOPoxVfB2PDNs3HBK43sr1A4NFcxxkMIx5dvXNzFRQvLZ34wczjGcvK5+mytk5Nii7k2/EE2wTBs80GPvqdMEeqU6ag6gC3zMCCZcdr53D5KAW9H5YWfmXP3J6kTKLk0k91KOt1JpfVpuSe/pr+6XdGsGT6KSBb1EA09CEDh+Ok3DcY5vhum2t+ntjyfH863m2HmwJp0UnXlFO6yNwikuCKY8Obh1RdQQLu4Xru5YnBa+ow1rhpX2E1mK4mjMjPeeoy+Wi7VvmAzglBiiEd0b6QImKKWuUTI4c8QFa01fYKDVEkqG+NGeXAmCtRXGr4lPSC+MixwFxY0Kx5i4F0YV/e6oWMKOLiScfrQtocjuCy5jBUw4tr9FXCacrgieqAPZJsttkRN0Q/PlPrXtQ/WFp60CJDJU4B3oEDU8R8iRMshdzR3iZPEiq7pfSYk333LYHrldjMzRyQULEVhBmsJpbOLaK1BzfFZlBtrDy9nm8SY67xTon43wP9YzIQchvQJEllIMWwmENT/SLQkFso=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
